### ISSUE TITLE
Compile Error on 3.1 update

### ISSUE THREAD

**Issue by rlbaltha** [oat-sa/bundle-lti1p3#30] opened 2020-12-14 18:58 UTC
Upon updating to 3.1 (with Symfony 4.4), I got the following compile error:
Compile Error: Declaration of OAT\Bundle\Lti1p3Bundle\DependencyInjection\S  
!!    ecurity\Factory\Message\LtiPlatformMessageSecurityFactory::create(Symfony\C  
!!    omponent\DependencyInjection\ContainerBuilder $container, string $id, array  
!!     $config, string $userProvider, ?string $defaultEntryPoint = NULL): array m  
!!    ust be compatible with Symfony\Bundle\SecurityBundle\DependencyInjection\Se  
!!    curity\Factory\SecurityFactoryInterface::create(Symfony\Component\Dependenc  
!!    yInjection\ContainerBuilder $container, $id, $config, $userProviderId, $def  
!!    aultEntryPointId)

**Comment by weaverryan** [comment] 2020-12-16 15:19
Hi!

I checked into this - and it's a "sort of" bug in the bundle that was introduced in sha: e9cbfa86a6a054915467e64e046864657c19b8d7

The problem is that Symfony 4.4 (which this bundle currently supports... and that's awesome) does *not* have scalar type-hints on the create method - https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/SecurityFactoryInterface.php#L37

And so, if you use Symfony 4.4, the `LtiPlatformMessageSecurityFactory::create()` method is "narrowing" the scope by adding the type-hints... which is not something that PHP likes :).

I believe the type-hints should be removed if you want to keep Symfony 4.4 support :)

**Comment by ekkinox** [comment] 2020-12-16 15:25
hello @rlbaltha and @weaverryan 

I've indeed recently added type hints, cause I was focused on SF 5.x, but composer.json indicate indeed the 4.4 support.

If you guys use this bundle on 4.4, please confirm and I'll remove then and bake you a new release.

Let me know :)

**Comment by weaverryan** [comment] 2020-12-16 15:30
Thanks for the fast reply @ekkinox! And no worries :). I've just created #31 - my hope is that we can easily add "lowest dependencies" to the test matrix - we'll see if I got the syntax right on my first try or not ;)

**Comment by ekkinox** [comment] 2020-12-16 16:14
Fixed in https://github.com/oat-sa/bundle-lti1p3/releases/tag/3.3.1

Many thx guys for spotting & fixing the issue ! Very appreciated :)

**Closed as completed by ekkinox** 2020-12-16 16:14 UTC
Labels: bug
